import React from 'react';
import  './Faq.css';

function FAQ() {
  return (
    <div className="policy-container">
      <h2>Frequently Asked Questions (FAQ)</h2>

      <h4>1. How does the AI generate lyrics and melodies?</h4>
      <p>
        Our AI uses natural language processing and machine learning algorithms to analyze the genre and description you provide. Based on that input, it creates unique lyrics and melodies tailored to your preferences. It's a creative tool designed to help inspire and assist with music creation.
      </p>

      <h4>2. Do I need to create an account to use the service?</h4>
      <p>
        No, you can use our website without creating an account or logging in. Simply select the genre, provide a description, and generate your lyrics and melody.
      </p>

      <h4>3. Is the content I generate free to use?</h4>
      <p>
        Yes! The lyrics and melodies you generate are free to use for personal, non-commercial purposes. If you'd like to use the generated content for commercial purposes, please contact us for further licensing options.
      </p>

      <h4>4. Can I modify the lyrics and melodies the AI generates?</h4>
      <p>
        Yes, you're free to modify the lyrics and melodies for your personal use. However, please note that the generated content remains your responsibility, and you are liable for any legal issues arising from its use.
      </p>

      <h4>5. How accurate is the AI-generated content?</h4>
      <p>
        Our AI is designed to provide creative and unique content based on your input, but it may not always produce perfect results. We encourage you to use it as a source of inspiration and adjust the output to suit your needs.
      </p>

      <h4>6. Will my data be saved or used for any other purpose?</h4>
      <p>
        No, we do not store any of the input data you provide. Your descriptions and the content generated by the AI are used only for the current session and are discarded afterward.
      </p>

      <h4>7. Can I share the content I create on social media?</h4>
      <p>
        Yes, you can share the generated lyrics and melodies on social media or with friends, as long as it is for personal, non-commercial purposes. If you'd like to use it commercially, please refer to our licensing terms.
      </p>

      <h4>8. How do I contact support if I have issues or questions?</h4>
      <p>
        If you need help or have any questions, feel free to reach out to us at <strong>[email address]</strong>. We'll be happy to assist you.
      </p>
    </div>
  );
}

export default FAQ;
