import React from 'react';
import './Licensing.css';

function Licensing() {
  return (
    <div className="policy-container">
      <h2>Licensing</h2>
      <p>Last Updated: 27/11/2024</p>

      <h4>Usage Rights:</h4>
      <ul>
        <li>
          <strong>Personal Use:</strong> You are granted a non-exclusive, worldwide license to use the lyrics and melodies generated by our service for personal, non-commercial purposes. This includes the right to share, listen to, or use the content in private projects. However, the content you generate is your responsibility, and you are liable for any legal issues arising from its use or distribution.
        </li>
        <li>
          <strong>Commercial Use:</strong> If you wish to use the generated lyrics and melodies for commercial purposes (e.g., in a product or service that generates revenue), you must obtain explicit permission from us. Please contact us at <strong>[email address]</strong> for licensing inquiries. Any commercial use is still your responsibility, and you are responsible for ensuring that your use complies with applicable laws.
        </li>
        <li>
          <strong>Modification and Redistribution:</strong> You may not modify, redistribute, or claim the generated content as your own, except as allowed by the personal use license above.
        </li>
      </ul>

      <h4>No Ownership:</h4>
      <p>
        You do not own the rights to the AI-generated lyrics or melodies. The content is generated based on your input and is licensed to you under the terms stated above.
      </p>

      <h4>Legal Responsibility:</h4>
      <p>
        You acknowledge that you are solely responsible for any legal consequences arising from the use, modification, or distribution of the generated content. We disclaim all responsibility for any legal claims or issues that may arise from the content you generate using our service.
      </p>

      <h4>Contact Us:</h4>
      <p>
        For further licensing inquiries, please contact us at <strong>[email address]</strong>.
      </p>
    </div>
  );
}

export default Licensing;
