import React from 'react';
import './TermsOfService.css';

function TermsOfService() {
  return (
    <div className="policy-container">
      <h2>Terms of Service</h2>
      <p>Last Updated: 27/11/2024</p>

      <h4>Use of the Service:</h4>
      <ul>
        <li>
          You may use our website to generate lyrics and melodies based on your input (e.g., genre, lyric description). You are responsible for ensuring that your input is appropriate, lawful, and does not infringe any rights.
        </li>
        <li>Our service does not require user accounts, and there is no need to log in.</li>
      </ul>

      <h4>Content Generated by the Service:</h4>
      <ul>
        <li>
          All lyrics and melodies generated by the website are for personal use only, unless otherwise specified.
        </li>
        <li>
          You are granted a <strong>non-exclusive</strong> license to use the generated content for personal, non-commercial purposes. However, the content you generate is your responsibility, and you are liable for any legal issues that may arise from using or distributing it.
        </li>
        <li>
          You may not resell, redistribute, or claim the generated content as your own without permission.
        </li>
      </ul>

      <h4>Limitation of Liability:</h4>
      <p>
        The website and its content are provided “as is” without warranty of any kind. We do not guarantee that the service will be error-free or uninterrupted. By using our service, you agree that any content you generate is at your own risk, and we are not liable for any legal consequences resulting from its use.
      </p>
      <p>
        We are not responsible for any loss, damage, or legal claims that may arise from the use or distribution of the generated content.
      </p>

      <h4>Changes to Terms:</h4>
      <p>
        We reserve the right to modify these terms at any time. We will notify users of significant changes by posting an updated version on our website.
      </p>

      <h4>Contact Us:</h4>
      <p>
        If you have any questions about our Terms of Service, please contact us at <strong>[placeholder email address]</strong>.
      </p>
    </div>
  );
}

export default TermsOfService;
